/**
 * Setup fresh Saskia + Rad Living stores with placeholder products.
 * Product names/descriptions will be generated by regenerate-products.ts
 *
 * Usage: npx tsx packages/api/scripts/setup-fresh-stores.ts
 */

import { config } from 'dotenv';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

config({ path: resolve(__dirname, '../../../.env.local') });
config({ path: resolve(__dirname, '../.env.local') });

import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.SUPABASE_URL || 'http://127.0.0.1:54321';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_SERVICE_KEY) {
  console.error('ERROR: SUPABASE_SERVICE_ROLE_KEY not set');
  process.exit(1);
}

const db = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

interface StoreSpec {
  name: string;
  vertical: string;
  description: string;
  imageFolder: string;
  imageExt: string;
  productCount: number;
}

const STORES: StoreSpec[] = [
  {
    name: 'Saskia',
    vertical: 'fashion',
    description: 'Premium Korean-inspired handbags',
    imageFolder: 'saskia',
    imageExt: 'jpg',
    productCount: 5,
  },
  {
    name: 'Rad Living',
    vertical: 'home_decor',
    description: 'Artisanal candles and home fragrance',
    imageFolder: 'rad-living',
    imageExt: 'webp',
    productCount: 5,
  },
];

async function deleteStore(namePattern: string) {
  const { data: oldStores } = await db.from('stores').select('id, slug').ilike('name', `%${namePattern}%`);
  if (oldStores && oldStores.length > 0) {
    const ids = oldStores.map(s => s.id);
    console.log(`  Deleting ${ids.length} old "${namePattern}" store(s)...`);
    for (const table of ['order_items', 'orders', 'cart_items', 'products', 'media_assets']) {
      await db.from(table).delete().in('store_id', ids);
    }
    await db.from('stores').delete().in('id', ids);
    console.log('  Deleted.');
  } else {
    console.log(`  No old "${namePattern}" stores found.`);
  }
}

async function createStore(spec: StoreSpec) {
  console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
  console.log(`  Setting up: ${spec.name}`);
  console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`);

  await deleteStore(spec.name);

  // Create demo owner
  const uniqueEmail = `${spec.name.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}@tatparya.local`;
  const { data: newUser, error: userErr } = await db.auth.admin.createUser({
    email: uniqueEmail,
    password: 'demo-password-123',
    email_confirm: true,
  });

  if (!newUser?.user) {
    console.error('Failed to create demo user:', userErr?.message);
    process.exit(1);
  }
  const ownerId = newUser.user.id;
  console.log(`  Owner: ${ownerId}`);

  // Create store
  const slug = `${spec.name.toLowerCase().replace(/\s+/g, '-')}-${Date.now().toString(36)}`;
  const { data: store, error: storeErr } = await db
    .from('stores')
    .insert({
      name: spec.name,
      slug,
      vertical: spec.vertical,
      description: spec.description,
      owner_id: ownerId,
      store_config: {},
      whatsapp_config: { businessPhone: '919876543210' },
    })
    .select()
    .single();

  if (storeErr || !store) {
    console.error('Failed to create store:', storeErr?.message);
    process.exit(1);
  }

  const storeId = store.id as string;
  console.log(`  Store: ${spec.name} (${slug})`);
  console.log(`  ID: ${storeId}`);

  // Create placeholder products
  const productRows = Array.from({ length: spec.productCount }, (_, i) => ({
    store_id: storeId,
    name: `Product ${i + 1}`,
    slug: `product-${i + 1}`,
    price: 2999,
    status: 'active',
    images: [{ originalUrl: `/uploads/${spec.imageFolder}/product-${i + 1}.${spec.imageExt}` }],
  }));

  const { data: products, error: prodErr } = await db
    .from('products')
    .insert(productRows)
    .select('id, name, slug');

  if (prodErr) {
    console.error('Failed to insert products:', prodErr.message);
    process.exit(1);
  }

  console.log(`  Products: ${products?.length || 0} created`);
  for (const p of products || []) {
    console.log(`    ${p.name} (${p.slug})`);
  }

  return slug;
}

async function main() {
  const slugs: string[] = [];
  for (const spec of STORES) {
    const slug = await createStore(spec);
    slugs.push(slug);
  }

  console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
  console.log(`  ALL STORES CREATED`);
  for (let i = 0; i < STORES.length; i++) {
    console.log(`  ${STORES[i]!.name}: ${slugs[i]}`);
  }
  console.log(`  Next: run regenerate-products then regenerate-design for each`);
  console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`);
}

main().catch((err) => {
  console.error('Script failed:', err);
  process.exit(1);
});
