/**
 * Setup fresh Saskia v2 store with 4 placeholder products.
 * Product names/descriptions will be generated by regenerate-products.ts
 *
 * Usage: npx tsx packages/api/scripts/setup-saskia-v2.ts
 */

import { config } from 'dotenv';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

config({ path: resolve(__dirname, '../../../.env.local') });
config({ path: resolve(__dirname, '../.env.local') });

import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.SUPABASE_URL || 'http://127.0.0.1:54321';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_SERVICE_KEY) {
  console.error('ERROR: SUPABASE_SERVICE_ROLE_KEY not set');
  process.exit(1);
}

const db = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

async function main() {
  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('  Setting up Saskia v2');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  // ── Delete all old Saskia stores ──
  const { data: oldStores } = await db.from('stores').select('id, slug').ilike('name', '%Saskia%');
  if (oldStores && oldStores.length > 0) {
    const ids = oldStores.map(s => s.id);
    console.log(`  Deleting ${ids.length} old Saskia store(s)...`);
    for (const table of ['order_items', 'orders', 'cart_items', 'products', 'media_assets']) {
      await db.from(table).delete().in('store_id', ids);
    }
    await db.from('stores').delete().in('id', ids);
    console.log('  Deleted.');
  } else {
    console.log('  No old Saskia stores found.');
  }

  // ── Create a demo owner ──
  const uniqueEmail = `saskia-v2-${Date.now()}@tatparya.local`;
  const { data: newUser, error: userErr } = await db.auth.admin.createUser({
    email: uniqueEmail,
    password: 'demo-password-123',
    email_confirm: true,
  });

  if (!newUser?.user) {
    console.error('Failed to create demo user:', userErr?.message);
    process.exit(1);
  }
  const ownerId = newUser.user.id;
  console.log(`  Owner: ${ownerId} (${uniqueEmail})`);

  // ── Create store ──
  const slug = `saskia-${Date.now().toString(36)}`;
  const { data: store, error: storeErr } = await db
    .from('stores')
    .insert({
      name: 'Saskia',
      slug,
      vertical: 'fashion',
      description: 'Premium Korean-inspired handbags',
      owner_id: ownerId,
      store_config: {},
      whatsapp_config: { businessPhone: '919876543210' },
    })
    .select()
    .single();

  if (storeErr || !store) {
    console.error('Failed to create store:', storeErr?.message);
    process.exit(1);
  }

  const storeId = store.id as string;
  console.log(`  Store: ${store.name} (${slug})`);
  console.log(`  ID: ${storeId}`);

  // ── Create 4 placeholder products ──
  const productRows = [1, 2, 3, 4].map(n => ({
    store_id: storeId,
    name: `Product ${n}`,
    slug: `product-${n}`,
    price: 2999,
    status: 'active',
    images: [{ originalUrl: `/uploads/saskia-v2/product-${n}.jpg` }],
  }));

  const { data: products, error: prodErr } = await db
    .from('products')
    .insert(productRows)
    .select('id, name, slug');

  if (prodErr) {
    console.error('Failed to insert products:', prodErr.message);
    process.exit(1);
  }

  console.log(`  Products: ${products?.length || 0} created`);
  for (const p of products || []) {
    console.log(`    ${p.name} (${p.slug})`);
  }

  console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
  console.log(`  SETUP COMPLETE`);
  console.log(`  Store: ${slug}`);
  console.log(`  Next: run regenerate-products then regenerate-design`);
  console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`);
}

main().catch((err) => {
  console.error('Script failed:', err);
  process.exit(1);
});
